import './globals.css'
import { Inter } from 'next/font/google'
import {Header} from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main className='container'>{children}</main>
      </body>
    </html>
  )
}
